on:
  push:
    branches:
      - master

name: Release EyeTry

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Download JREs
        run: |
          chmod +x ./gradlew
          ./gradlew --stacktrace --info downloadAndExtractJREs
          chmod -R 777 build/jre

      - name: Generate releases
        run: |
          ./gradlew --stacktrace --info packageApp

      - name: Generate Windows Installer with InnoSetup
        run: |
          chmod -R 777 build/distributions
          chmod -R 777 build/jre
          ./gradlew --stacktrace --info generateWindowsInstallerInDocker

      - name: Get Env
        run: |
          echo "REPO_NAME=${{ github.repository }}" >> $GITHUB_ENV

      - name: New tag
        id: new-tag
        run: |
          LATEST_RELEASE_INFO=$(curl -s https://api.github.com/repos/${{ env.REPO_NAME }}/releases/latest)
          NEW_VERSION_LINK=$(echo "$LATEST_RELEASE_INFO" | grep "browser_download_url.*EyeTry*" | cut -d: -f2,3 | tr -d \")
          NEW_VERSION=$( echo "${NEW_VERSION_LINK}" | cut -d/ -f9)
          NEW_VERSION_NO_EXT=$( echo ${NEW_VERSION} | cut -d. -f1)
          NEW_VERSION_NAME=$(echo "$LATEST_RELEASE_INFO" | grep "name.*EyeTry*" | cut -d: -f2,3 | tr -d \" | head -n 1 | tr -d \,)
          GET_TAG=$(echo "$NEW_VERSION_NAME" | cut -d " " -f3)
          TAG_1=$(echo "$GET_TAG" | cut -d. -f1)
          TAG_2=$(echo "$GET_TAG" | cut -d. -f2)
          TAG_3=$(echo "$GET_TAG" | cut -d. -f3)
          NEW_TAG=$(echo "$(( $TAG_3 + 1 ))")
          TAG="${TAG_1}.${TAG_2}.${NEW_TAG}"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.new-tag.outputs.tag }}
          name: EyeTry ${{ steps.new-tag.outputs.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: "master"
          prerelease: true
          draft: false
          artifacts: "./build/distributions/EyeTry-windows.zip,./build/distributions/EyeTry-windows-x64-installer.exe"

